# Generated by Django 3.2.12 on 2022-03-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_imaga', models.ImageField(upload_to='image')),
                ('tital', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Artical_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.artical')),
            ],
        ),
    ]
